### ISSUE TITLE
哈喽，经常出现执行到连接到action地方时，没有连接日志信息

### ISSUE THREAD

**Issue by asiaon123** [P3TERX/ssh2actions#3]
![image](https://user-images.githubusercontent.com/5396968/108538964-5954b680-731a-11eb-9436-2ee65c4b199e.png)

**Comment by Dboykey** [comment]
同问！

**Comment by superabbite1** [comment]
同问啊

**Comment by rokibhasansagar** [comment]
The Actions Log seems to load a bit late for other action scripts too, not just this one.
So, it's a normal internal problem that we all have to face.
